version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgis/postgis:12-3.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Welcome01
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:4.16
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin-servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - app-network
    entrypoint: >
      sh -c "sleep 10 &&
      /entrypoint.sh"

volumes:
  postgres:
  pgadmin:

networks:
  app-network:
    driver: bridge
